//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказанныеТовары
    {
        public Nullable<int> ID_заказа { get; set; }
        public Nullable<int> ID_товара { get; set; }
        public Nullable<int> Количество_товара_в_заказе { get; set; }
        public Nullable<decimal> Стоимость_товара_в_заказе { get; set; }
        public int ID_заказ_товары { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
